const mongoose = require("mongoose")
const Schema = mongoose.Schema

const userSchema = new Schema({
    firstName:{
        type:String,
        required:true
    },
    lastName:{
        type:String,
        required:true
    },
    email:{
        type:String,
        required:true,
        unique:true,
        lowercase:true
    },
    password:{
        type:String,
        required:true
    },
    role:{
        type:String,
        default:"user",
        enum:["user","admin","seller"] 
    },
    profilePic:{
        type:String,
        default:""
    },
    status:{
        type:String,
        default:"active",
        enum:["active","inactive","deleted","blocked"]
    },
    isVerified:{
        type:Boolean,
        default:false
    },
    otp:{
        type:String,
        default:""
    },
    createdAt:{
        type:Date,
        default:Date.now
    }
})
module.exports=mongoose.model("users",userSchema)